steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/wasd-gamers:base || exit 0

- id: base
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'wasd-gamers:base',
    '-t', 'gcr.io/$PROJECT_ID/wasd-gamers:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/wasd-gamers:base',
    '.'
  ]

- id: base_cache
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wasd-gamers:base']

- id: test
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/wasd-gamers:latest',
    '.'
  ]

- id: coverage
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['test']
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/wasd-gamers:coverage',
    '.'
  ]

images: ['gcr.io/$PROJECT_ID/wasd-gamers:base', 'gcr.io/$PROJECT_ID/wasd-gamers:latest', 'gcr.io/$PROJECT_ID/wasd-gamers:coverage']